package app

const (
	authzMsgExec                        = "/cosmos.authz.v1beta1.MsgExec"
	authzMsgGrant                       = "/cosmos.authz.v1beta1.MsgGrant"
	authzMsgRevoke                      = "/cosmos.authz.v1beta1.MsgRevoke"
	bankMsgSend                         = "/cosmos.bank.v1beta1.MsgSend"
	bankMsgMultiSend                    = "/cosmos.bank.v1beta1.MsgMultiSend"
	distrMsgSetWithdrawAddr             = "/cosmos.distribution.v1beta1.MsgSetWithdrawAddress"
	distrMsgWithdrawValidatorCommission = "/cosmos.distribution.v1beta1.MsgWithdrawValidatorCommission"
	distrMsgFundCommunityPool           = "/cosmos.distribution.v1beta1.MsgFundCommunityPool"
	distrMsgWithdrawDelegatorReward     = "/cosmos.distribution.v1beta1.MsgWithdrawDelegatorReward"
	feegrantMsgGrantAllowance           = "/cosmos.feegrant.v1beta1.MsgGrantAllowance"
	feegrantMsgRevokeAllowance          = "/cosmos.feegrant.v1beta1.MsgRevokeAllowance"
	legacyGovMsgVoteWeighted            = "/cosmos.gov.v1beta1.MsgVoteWeighted"
	legacyGovMsgSubmitProposal          = "/cosmos.gov.v1beta1.MsgSubmitProposal"
	legacyGovMsgDeposit                 = "/cosmos.gov.v1beta1.MsgDeposit"
	legacyGovMsgVote                    = "/cosmos.gov.v1beta1.MsgVote"
	govMsgVoteWeighted                  = "/cosmos.gov.v1.MsgVoteWeighted"
	govMsgSubmitProposal                = "/cosmos.gov.v1.MsgSubmitProposal"
	govMsgDeposit                       = "/cosmos.gov.v1.MsgDeposit"
	govMsgVote                          = "/cosmos.gov.v1.MsgVote"
	stakingMsgEditValidator             = "/cosmos.staking.v1beta1.MsgEditValidator"
	stakingMsgDelegate                  = "/cosmos.staking.v1beta1.MsgDelegate"
	stakingMsgUndelegate                = "/cosmos.staking.v1beta1.MsgUndelegate"
	stakingMsgBeginRedelegate           = "/cosmos.staking.v1beta1.MsgBeginRedelegate"
	stakingMsgCreateValidator           = "/cosmos.staking.v1beta1.MsgCreateValidator"
	vestingMsgCreateVestingAccount      = "/cosmos.vesting.v1beta1.MsgCreateVestingAccount"
	ibcMsgTransfer                      = "/ibc.applications.transfer.v1.MsgTransfer"

	nftMsgIssueDenom    = "/furymod.nft.MsgIssueDenom"
	nftMsgTransferDenom = "/furymod.nft.MsgTransferDenom"
	nftMsgMintNFT       = "/furymod.nft.MsgMintNFT"
	nftMsgEditNFT       = "/furymod.nft.MsgEditNFT"
	nftMsgTransferNFT   = "/furymod.nft.MsgTransferNFT"
	nftMsgBurnNFT       = "/furymod.nft.MsgBurnNFT"

	mtMsgIssueDenom    = "/furymod.mt.MsgIssueDenom"
	mtMsgTransferDenom = "/furymod.mt.MsgTransferDenom"
	mtMsgMintMT        = "/furymod.mt.MsgMintMT"
	mtMsgEditMT        = "/furymod.mt.MsgEditMT"
	mtMsgTransferMT    = "/furymod.mt.MsgTransferMT"
	mtMsgBurnMT        = "/furymod.mt.MsgBurnMT"
)
